---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-name
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
    - name: logger
      image: mylogger:latest
      ports:
        - containerPort: 8089
          protocol: UDP
